name: Build image

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: Te4g/workflows/.github/workflows/docker-build-publish-ghcr.yml@main
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/my-api
      dockerfile: ./Dockerfile
      image-tag: sha-${{ github.sha }}
      floating-tag: main
