name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: Te4g/workflows/.github/workflows/deploy.yml@main
    with:
      artifact-path: dist
    secrets:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
