name: Deploy

on:
    workflow_call:
        inputs:
            artifact-path:
                description: 'Path to extract the artifact to'
                required: false
                type: string
                default: '.'
        secrets:
            DEPLOY_HOST:
                required: true
            DEPLOY_PORT:
                required: true
            DEPLOY_USER:
                required: true
            DEPLOY_KEY:
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Download artifacts
                uses: actions/download-artifact@v4
                with:
                    name: build
                    path: ${{ inputs.artifact-path }}
                continue-on-error: true
            -   name: Setup SSH key
                run: |
                    mkdir -p ~/.ssh
                    echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa
            -   name: Create destination directory
                run: |
                    ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "mkdir -p /srv/www/${{ github.event.repository.name }}"
            -   name: Deploy with rsync
                run: |
                    rsync -avz --delete --exclude-from ".rsyncignore" -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT }}" ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/srv/www/${{ github.event.repository.name }}
            -   name: Build containers
                run: |
                    ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd /srv/www/${{ github.event.repository.name }} && make install-prod"
